spring:
   main:
      web-application-type: none
logging:
  level:
    ca:
      gov:
        bc: DEBUG
bcgov:
  access:
    input:
      document-type: test-doc
      plugin: sftp
      sftp:
        host: localhost
        port: 2222
        username: master
        password: master
        local-directory: C:/Users/177226/Downloads/Justice
        remote-directory: /home/master/
    output:
      document-type: test-doc
      plugin: console
