
logging:
  level:
    ca:
      gov:
        bc: DEBUG
bcgov:
  access:
    input:
      document-type: test-doc
      plugin: console
    output:
      document-type: test-doc
      plugin: console
      console:
         format: xml
