main:
  web-application-type: none
logging:
  level:
    ca:
      gov:
        bc: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} %X{transaction.filename} %X{transaction.id} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} %X{transaction.filename} - %msg%n"
spring:
  redis:
    host: localhost
    port: 6379
    password: admin
bcgov:
  access:
    input:
      sender: bcgov
      document-type: test-doc
      plugin: sftp
      sftp:
        port: 22
        username: admin
        password: admin
        remoteDirectory:  upload
        filterPattern: .*.xml
        cron: '*/5 * * * * ?'
        maxMessagePerPoll: 1
        allowUnknownKeys: true
        knownHostFile: ${KNOWN_HOSTS}
    output:
      document-type: test-doc
      plugin: console