spring:
   main:
      web-application-type: NONE
logging:
  level:
    ca:
      gov:
        bc: DEBUG
bcgov:
  access:
    input:
      document-type: test-doc
      plugin: rabbitmq
      rabbitmq:
         retry-delay: 5000
         retry-count: 10
    output:
      document-type: test-doc
      plugin: console
